### ISSUE TITLE
[BUG] Athletic EDIT HUD missing buttons

### ISSUE THREAD

**Issue by FreyaIthildur** [Collaboratives/MeshbodyBugReports#13]
**Describe the bug**
The little sidebar that is with every HUD is missing onthe Body page. Or better, buttons seems tobe alphaed out. Clicking on the general position makes the function work. Both on full product and DEMO

**To Reproduce**
1. Add your Athletic EDIT hud
2. See error

**Expected behavior**
The icons should be visible. 

**Screenshots**
https://prnt.sc/tAefh3ml93LI

**Product (please complete the following information):**
 - Name: Legacy Athletic / Try It On! Legacy Athletic
 - Version 1.6

**Comment by Collaboratives** [comment]
fixed textures
