### ISSUE TITLE
[BUG] Ankle lock wiggle

### ISSUE THREAD

**Issue by FreyaIthildur** [Collaboratives/MeshbodyBugReports#18]
**Describe the bug**
Animation of the ankle lock is producing a wiggle each time the animation is played

**To Reproduce**
1. Turn off all the AOs (or use them makes no difference)
2. Turn on the ankle lock
3. See the foot wiggle

**Expected behavior**
The feet shouldn't wiggle

**Screenshots**
https://gyazo.com/1a0216918aecfa2b2ab30dafc9acf571

**Product (please complete the following information):**
 - Name: All the bodies
 - Version 1.6

**Additional context**
Probably it's the animation that does a wiggle?  Maybe it's not script related but on the animation itself not being static but having a slow movement?

**Comment by Collaboratives** [comment]
Animation fixed. Will be part of next. update
